app/urls.py
from django.conf.urls import url
from app.views import signup, article_home,article_create,article_detail

urlpatterns=[
    url(r'^signup/$',signup,name='signup'),
    url(r'^$',article_home,name='article'),
    url(r'^create/$',article_create,name='article_create'),
    url(r'^detail/(?P<pk>\d+)/$',article_detail,name='article_detail')
]

article/urls.py
from django.conf.urls import url
from .views import article_home,article_create,article_detail,comment_create
urlpatterns=[
    url(r'^$',article_home,name='article'),
    url(r'^create/$',article_create,name='article_create'),
    url(r'^detail/(?P<pk>\d+)/$',article_detail,name='article_detail'),
    url(r'^comment/create/(?P<pk>\d+)/$', comment_create, name='comment_create'),

]

login/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.views.generic.base import TemplateView
from app import views
from room.views import index


urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^article/', include('article.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^about/$', TemplateView.as_view(template_name='about.html'), name='about'),
    url(r'^profile/$', TemplateView.as_view(template_name='profile/view_profile.html'), name='profile'),
    url(r'^login/$', auth_views.login, {'template_name': 'authentication/login.html'}, name='login'),
    url(r'^logout/$', auth_views.logout, {'template_name': 'authentication/logged_out.html'}, name='logout'),
    url(r'^signup/$',views.signup,name='signup'),
    url(r'^chat/$',index,name='chat'),
    url(r'^update/$',views.update_profile,name='update'),
    url(r'^account_activation_sent/$', views.account_activation_sent, name='account_activation_sent'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.activate, name='activate'),
]

article/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User


# Create your models here.



class Article(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=30)
    description = models.CharField(max_length=2000)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title
class Comment(models.Model):
    article=models.ForeignKey(Article,on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    comment = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.comment

article/forms.py
from django import forms
from .models import Article,Comment


class ArticleForm(forms.Form):
    title=forms.CharField(max_length=100)
    description=forms.CharField(widget=forms.Textarea)
class CommentForm(forms.Form):
    comment= forms.CharField(max_length=200,required=True)

article/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render,redirect, get_object_or_404
from .models import Article, Comment
from .forms import ArticleForm, CommentForm
# Create your views here.

def article_home(request):
    articles = Article.objects.filter(user=request.user)
    return render(request, 'article/article_home.html', {
        'articles': articles
    })
def article_create(request):
    if request.method == 'POST':
        form = ArticleForm(request.POST)
        if form.is_valid():
            user = request.user
            title = form.cleaned_data.get('title')
            description = form.cleaned_data.get('description')
            article = Article(user=user, title=title, description=description)
            article.save()
            return redirect('article')
    else:
        form = ArticleForm
    return render(request, 'article/article_create.html', {'form': form})


def article_detail(request, pk):
    article = get_object_or_404(Article, pk=pk)
    return render(request, 'article/article_detail.html', {'article': article})
def comment_create(request,pk):
    articles=Article.objects.all().distinct()
    if request.method== 'POST':
        form= CommentForm(request.POST)
        if form.is_valid():
            comment=Comment(user=request.user,article_id=pk,comment=form.cleaned_data.get('comment'))
            comment.save()

            return redirect('home')
    else:
        form=CommentForm
    return render(request,'home.html',{
        'form':form,
        'articles':articles
    })

templates/article/article_create.html
{% extends 'base.html' %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-lg-6">
                <form method="post">
                    <div class="form-group">
                                             {% csrf_token %}
                    <label for="title">Title</label>
                    <input type="text" class="form-control" id="title" name="title">
                    </div>
                    <div class="form-group">
                    <label for="description">Description</label>
                    {% csrf_token %}
                    <textarea type="text" class="form-control" id="description" name="description" rows="7"></textarea>
                    </div>
                    <button type="submit" class="btn btn-default">Submit</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

templates/article/article_detail.html
{% extends 'base.html' %}
{% block content %}

    {{ article.title }}
    {{ article.description }}
    {{ article.user.username }}
    {{ article.created_at }}
{% endblock %}

templates/article/article_home.html
{% extends 'base.html' %}
{% block content %}
    <div class="container">

      <div class="row">

        <!-- Post Content Column -->
        <div class="col-lg-8">
            <a class="btn btn-primary" href="{% url 'article_create' %}">Create</a>
          <!-- Title -->
           {% for article in articles %}
          <h1 class="mt-4">{{ article.title }}</h1>
          <!-- Author -->
          <p class="lead">
            by
            <a href="#">{{ article.user.username }}</a>
          </p>

          <hr>

          <!-- Date/Time -->
          <p>Posted on {{ article.created_at }}</p>

          <hr>

          <!-- Preview Image -->
{#          <img class="img-fluid rounded" src="http://placehold.it/900x300" alt="">#}
{##}
{#          <hr>#}

          <!-- Post Content -->
               <p> {{ article.description }}</p>
          <hr>
           <h3 class="mt-4">Comments</h3>
           <hr>
            {% for comment in article.comment_set.all %}

          <!-- Single Comment -->
          <div class="media mb-4">
            <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
            <div class="media-body">
              <h5 class="mt-0">{{ comment.user.username }}</h5>
              {{ comment.comment }}
            </div>
          </div>
                {% endfor %}
            {% endfor %}

        </div>



{% endblock %}